### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Charliebegood**

### CODE REVIEW

**Comment by Schemetrical** [comment]
:( same here

**Comment by Charliebegood** [comment]
I know... First thing I did was to check yours! When I look at your app, still don't get why you didn't get a scholarship. :( I'll try again next year.

**Comment by Charliebegood** [comment]
Though the rules had changed this year. Maybe they aren't looking for "About me" apps anymore :(

**Comment by Schemetrical** [comment]
I didn't write an about me, and I was rejected. Many who did weren't. Be creative :)

**Comment by Charliebegood** [comment]
I guess! :)

**Pull request merged**
