### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cyhsutw**
Stay at home and watch videos this year 😂

### CODE REVIEW

**Comment by cyhsutw** [comment]
thank you @Schemetrical for maintaining this repo 🙏

**Comment by Schemetrical** [comment]
NP :) I'll stay at home and cry too while I update this repo

**Comment by cyhsutw** [comment]
that's really sad 
hope you get the ticket next year 💪

**Comment by Schemetrical** [comment]
You too!

**Pull request merged**
