### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by termorrell**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Can you change technologies to two main ones, such as "A & B"? Thanks

**Comment by termorrell** [comment]
@Schemetrical Done! Thanks for adding that extra column btw 👍

**Comment by Schemetrical** [comment]
Thank @k3zi :P
Few more hours, good luck!

**Comment by termorrell** [comment]
Thanks for adding the extra column @k3zi 👍

**Pull request merged**
