### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hyerra**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Do you mind adding your last name? Thanks

**Comment by hyerra** [comment]
Ok, I updated with my last name 👍

**Comment by Schemetrical** [comment]
You have one extra pipe after `submitted`

**Comment by hyerra** [comment]
Does it look better now?

**Comment by Schemetrical** [comment]
You removed too much haha, keep the `submitted`, but make sure there are 6 pipes in total

**Comment by hyerra** [comment]
I just removed the extra pipe after `submitted`. Sorry about that.

**Comment by hyerra** [comment]
I removed the entire submitted. I just changed it back. It should look fine now.

**Comment by Schemetrical** [comment]
Change it to `|[Harish Yerra](https://www.twitter.com/harishyerra4)||Submitted|3D Touch & MapKit|Accepted|`
You're still missing a pipe before submitted :P

**Comment by hyerra** [comment]
Ok does it look better now?

**Comment by Schemetrical** [comment]
Alright congrats :)

**Comment by hyerra** [comment]
Thanks :)

**Pull request merged**
