### PR TITLE
Added Brendan Boyle

### PR DESCRIPTION
**Pull request by bcbee**

### CODE REVIEW

**Comment by Schemetrical** [comment]
If you submitted an App Store app, there is no need to include the source unless you submitted an ipa as well :)

**Comment by bcbee** [comment]
First off, thanks for doing this!
I submitted as an IPA because the latest AppStore update was still in review, but they are essentially the same now. Would you like me to remove the AppStore or source link?

**Comment by Schemetrical** [comment]
That's alright actually. It's just to let others see how many apps one submitted.

**Comment by Schemetrical** [comment]
Good luck!

**Pull request merged**
