### PR TITLE
Added Florian Pfisterer

### PR DESCRIPTION
**Pull request by FlorianPfisterer**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Can you list only two main technologies, and for 3D Touch don't use the dash. Thanks :)

**Comment by FlorianPfisterer** [comment]
Alright, done. Thank you!

**Comment by Schemetrical** [comment]
Grats, it's so soon!

**Comment by FlorianPfisterer** [comment]
Thanks! It's a pity you weren't accepted as you contribute so much to the community! Just wanted to let you know how much I learned from your WWDC15 submission!

**Comment by Schemetrical** [comment]
Haha thanks :), I call it the curse of the WWDC repo. For the past two years the repo managers were all rejected :P.

**Pull request merged**
