### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeremystucki**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Do you mind splitting up the entries, alphabetising, and also removing "submitted" for the last field? Thanks :p
I'm busy on my app as well!

**Comment by Schemetrical** [comment]
Just remove the "Submitted" from the last column thanks :)

**Comment by jeremystucki** [comment]
sorry about that

**Comment by jeremystucki** [comment]
Sorry I have an issue with Github at the moment. Would you mind making the change?

**Comment by Schemetrical** [comment]
Sure

**Comment by Schemetrical** [comment]
Good luck :-)
Somehow github didn't recognise the merge but it's done!

**Pull request closed without merging**
