### PR TITLE
Added my app technologies

### PR DESCRIPTION
**Pull request by kylespadaro-zz**
I added my app technologies.

### CODE REVIEW

**Comment by Schemetrical** [comment]
Can you remove the extra pipe, thanks!

**Comment by kylespadaro-zz** [comment]
@Schemetrical done

**Comment by Schemetrical** [comment]
You didn't add that commit yet

**Comment by santieduardo** [comment]
Add me, please - Eduardo Santi

**Comment by Schemetrical** [comment]
@santieduardo can you please open a pull request with your info, thanks.

**Comment by santieduardo** [comment]
@Schemetrical thank you very much

**Comment by kylespadaro-zz** [comment]
Maybe I had to create a new pull request -- refer to the new one I created as well

**Comment by kylespadaro-zz** [comment]
I'm going to close this one, since apparently I didn't create a pull request after removing the pipe. Refer to my new pull request #85.

**Comment by kylespadaro-zz** [comment]
Forget about the previous comment. It appears you merged it, so case closed.

**Pull request closed without merging**
