### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alustinight**

### CODE REVIEW

**Comment by kylespadaro-zz** [comment]
Will there be a page for 2017 apps? Applications just opened today, so I'm assuming you are going to wait until after the deadline

**Comment by Schemetrical** [comment]
I danses it off to @AndrewKe, but if you want to you can help take over too. I'm slightly busy ATM.

**Comment by kylespadaro-zz** [comment]
Sure, I can help

**Comment by Schemetrical** [comment]
Gave you owner access.

**Comment by kylespadaro-zz** [comment]
Ok I created a repository for 2017.

**Pull request merged**
