### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kylespadaro-zz**
Updated technologies (I provided the wrong app technology) and added my status.

### CODE REVIEW

**Comment by kylespadaro-zz** [comment]
Sorry, I keep making errors with the technologies. It's final now.

**Comment by Schemetrical** [comment]
Use & instead of and, thanks

**Comment by kylespadaro-zz** [comment]
@Schemetrical done.

**Comment by k3zi** [comment]
Had to manually merge (I think git was complaining that you deleted the fork) but I got it updated. Congrats!

**Comment by kylespadaro-zz** [comment]
@k3zi I think you merged the wrong one, because the new technologies I added aren't on the list.

**Comment by k3zi** [comment]
@kylespadaro Gotcha! Should be fixed now

**Comment by kylespadaro-zz** [comment]
@k3zi it is, thanks!

**Pull request closed without merging**
