### PR TITLE
Added Sebastian Dobrincu

### PR DESCRIPTION
**Pull request by sebyddd**

### CODE REVIEW

**Comment by Schemetrical** [comment]
can you move your name up two slots so its in alphabetical order? thanks :)

**Comment by sebyddd** [comment]
Done :)

**Comment by Schemetrical** [comment]
Awesome good luck!

**Comment by sebyddd** [comment]
Thanks @Schemetrical. Hope to see you there this year! :)

**Comment by Schemetrical** [comment]
Same!

**Comment by Schemetrical** [comment]
Also, the video is private, could you fix that, thanks!

**Comment by sebyddd** [comment]
It's scheduled to be public at 5PM UTC-8, right when the submissions are closed :).

**Comment by Schemetrical** [comment]
Smart :D

**Pull request merged**
