### PR TITLE
Rejected, BRUTALLY.

### PR DESCRIPTION
**Pull request by hharanm**

### CODE REVIEW

**Comment by Schemetrical** [comment]
Can you change it to "Core Motion & GLKit", thanks.

**Comment by hharanm** [comment]
Sure!

**Comment by Schemetrical** [comment]
You dont have to close a pr to add commits :)

**Comment by hharanm** [comment]
I'm new to GitHub...

**Comment by hharanm** [comment]
Is it fixed now?

**Comment by Schemetrical** [comment]
Yep

**Pull request merged**
