### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RupiDev**

### CODE REVIEW

**Comment by k3zi** [comment]
Was this a mistake? I see your name already on the list in a different spot

**Comment by RupiDev** [comment]
No it wasn't a mistake. I don't see my name on the list

**Comment by k3zi** [comment]
It's a little farther down below `Vignesh Varadarajan`:
untitled

**Comment by RupiDev** [comment]
Yes that is the same project. QSport was done by 4 people. I was one of those people, but my name is not Vincent. I would like my personal name, Rupin Bhalla, on the sheet.

**Comment by Schemetrical** [comment]
You should edit it to show your name then, check the diff, it shows Vincent.

**Comment by vincent144** [comment]
@RupiDev just submit a PR for the `patch-1` branch, i'm not sure why this `patch-2` branch has my name in it

**Pull request closed without merging**
