### PR TITLE
Updated status :/

### PR DESCRIPTION
**Pull request by BenchR267**

### CODE REVIEW

**Comment by ezhes** [comment]
Did you get an email yet? I'd wait until you get an email before you merge

**Comment by Schemetrical** [comment]
@shusain93 yup.

**Comment by ezhes** [comment]
Aw that sucks man. Better luck next year. Haven’t got an email yet but I don’t have an event button in my dev account so I’m prepared for bad news from the looks of it

**Comment by Schemetrical** [comment]
Sorry man :(

**Comment by BenchR267** [comment]
Yeah, the mail arrived, but I was sure before..

**Pull request merged**
