### PR TITLE
Add Charles Aubert

### PR DESCRIPTION
**Pull request by Charliebegood**
https://github.com/wwdc/2016/commit/9a2ae9b5bb98e4b0162813b640395438b2254158

### CODE REVIEW

**Comment by Schemetrical** [comment]
Can you change it to two main technologies? Thanks

**Comment by Charliebegood** [comment]
Done :)

**Comment by Schemetrical** [comment]
Do you mind making it MapKit & Scene/SpriteKit just for neatness sake :P Thanks!

**Comment by Charliebegood** [comment]
No prob ;) There you go !

**Comment by Schemetrical** [comment]
Alright good luck!

**Pull request merged**
