### PR TITLE
Hari's Info

### PR DESCRIPTION
**Pull request by hharanm**
Hari's Info

### CODE REVIEW

**Comment by Schemetrical** [comment]
Do you mind using your full name to ensure consistency? Thanks!

**Comment by hharanm** [comment]
It's kinda a big, I prefer it this way. I'll change it if you insist!

**Comment by Schemetrical** [comment]
Alright sure if you prefer it this way!

**Comment by Schemetrical** [comment]
Good luck, 3 days left!

**Comment by hharanm** [comment]
Thanks! We'll meet in SFO hopefully!

**Comment by Schemetrical** [comment]
I hope so!

Yichen

**Pull request merged**
